### ISSUE TITLE
Add dimension as input to create_model

### ISSUE THREAD

**Issue by jamaliki** [openai/guided-diffusion#4]
Hi, thank you so much for open sourcing the code. I was planning on using this repo for 3d images and although I can see that the UNet class allows 3d inputs, the "dims" keyword is not passed through the create_model function in script_util.py.
If it is alright with the owners of the repo, I would like to push my change that would allow this. This change would keep the default dimension to 2 so that no breaking changes hopefully result.

**Comment by unixpickle** [comment]
At the moment we plan to keep this codebase mostly frozen, so that it reflects the state of our code at the time of the paper. It's less of a library / tool and more of a reference codebase.

Feel free to fork this project, improve upon it, and promote your fork! We would love to see these types of projects :)

**Comment by jamaliki** [comment]
Understood :) That is what I ended up doing. Thanks for making it available!
